celebrities = [
    {"name": "Cristiano Ronaldo", "age": 39, "profession": "Footballer", "Instagram followers": 617, "country": "Portugal"},
    {"name": "Lionel Messi", "age": 36, "profession": "Footballer", "Instagram followers": 488, "country": "Argentina"},
    {"name": "Dwayne Johnson", "age": 51, "profession": "Actor", "Instagram followers": 397, "country": "USA"},
    {"name": "Kylie Jenner", "age": 26, "profession": "Entrepreneur", "Instagram followers": 399, "country": "USA"},
    {"name": "Ariana Grande", "age": 30, "profession": "Singer", "Instagram followers": 379, "country": "USA"},
    {"name": "Selena Gomez", "age": 31, "profession": "Singer", "Instagram followers": 429, "country": "USA"},
    {"name": "Kim Kardashian", "age": 43, "profession": "Media Personality", "Instagram followers": 364, "country": "USA"},
    {"name": "Beyoncé", "age": 42, "profession": "Singer", "Instagram followers": 319, "country": "USA"},
    {"name": "Justin Bieber", "age": 29, "profession": "Singer", "Instagram followers": 291, "country": "Canada"},
    {"name": "Taylor Swift", "age": 34, "profession": "Singer", "Instagram followers": 282, "country": "USA"},
    {"name": "Kendall Jenner", "age": 28, "profession": "Model", "Instagram followers": 293, "country": "USA"},
    {"name": "Virat Kohli", "age": 35, "profession": "Cricketer", "Instagram followers": 269, "country": "India"},
    {"name": "Neymar Jr", "age": 32, "profession": "Footballer", "Instagram followers": 218, "country": "Brazil"},
    {"name": "Zendaya", "age": 27, "profession": "Actress", "Instagram followers": 179, "country": "USA"},
    {"name": "Robert Downey Jr.", "age": 58, "profession": "Actor", "Instagram followers": 106, "country": "USA"},
    {"name": "Chris Hemsworth", "age": 40, "profession": "Actor", "Instagram followers": 58, "country": "Australia"},
    {"name": "Shakira", "age": 47, "profession": "Singer", "Instagram followers": 89, "country": "Colombia"},
    {"name": "Rihanna", "age": 35, "profession": "Singer", "Instagram followers": 152, "country": "Barbados"},
    {"name": "LeBron James", "age": 39, "profession": "Basketball Player", "Instagram followers": 160, "country": "USA"},
    {"name": "Emma Watson", "age": 33, "profession": "Actress", "Instagram followers": 104, "country": "UK"},
    {"name": "Drake", "age": 37, "profession": "Rapper", "Instagram followers": 139, "country": "Canada"},
    {"name": "Billie Eilish", "age": 22, "profession": "Singer", "Instagram followers": 116, "country": "USA"},
    {"name": "Chris Evans", "age": 42, "profession": "Actor", "Instagram followers": 27, "country": "USA"},
    {"name": "Tom Holland", "age": 27, "profession": "Actor", "Instagram followers": 67, "country": "UK"},
    {"name": "Shah Rukh Khan", "age": 58, "profession": "Actor", "Instagram followers": 45, "country": "India"},
    {"name": "Priyanka Chopra", "age": 41, "profession": "Actress", "Instagram followers": 90, "country": "India"},
    {"name": "Will Smith", "age": 55, "profession": "Actor", "Instagram followers": 73, "country": "USA"},
    {"name": "Jason Momoa", "age": 44, "profession": "Actor", "Instagram followers": 18, "country": "USA"},
    {"name": "Keanu Reeves", "age": 59, "profession": "Actor", "Instagram followers": 0, "country": "Canada"},
    {"name": "David Beckham", "age": 48, "profession": "Footballer", "Instagram followers": 84, "country": "UK"},
    {"name": "Elon Musk", "age": 52, "profession": "Entrepreneur", "Instagram followers": 40, "country": "USA"},
    {"name": "Jennifer Lopez", "age": 54, "profession": "Singer", "Instagram followers": 248, "country": "USA"},
    {"name": "Gigi Hadid", "age": 28, "profession": "Model", "Instagram followers": 79, "country": "USA"},
    {"name": "Dua Lipa", "age": 28, "profession": "Singer", "Instagram followers": 89, "country": "UK"},
    {"name": "Miley Cyrus", "age": 31, "profession": "Singer", "Instagram followers": 211, "country": "USA"},
    {"name": "Ed Sheeran", "age": 33, "profession": "Singer", "Instagram followers": 45, "country": "UK"},
    {"name": "Adele", "age": 35, "profession": "Singer", "Instagram followers": 56, "country": "UK"},
    {"name": "Katy Perry", "age": 39, "profession": "Singer", "Instagram followers": 110, "country": "USA"},
]

# Example: Print the first celebrity
